@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.torchbandolier.crafting.recipe;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;